# Generated by Django 5.2 on 2025-04-19 13:16

import IpefaSup3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IpefaSup3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentMail',
            field=models.EmailField(max_length=254, unique=True, validators=[IpefaSup3.models.validate_student_email]),
        ),
    ]
