# Generated by Django 5.2 on 2025-04-09 10:59

import IpefaSup3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IpefaSup3', '0002_alter_administrator_password_alter_educator_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentMail',
            field=models.EmailField(max_length=254, unique=True, validators=[IpefaSup3.models.custom_email_validator]),
        ),
    ]
